{
  "hash": "da312c2a4eee96360f7fe013c069e1f4",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"The Causal Compass: From Classical DiD to the Callaway–Sant'Anna Framework\"\ndescription: \"Why staggered rollout analyses using TWFE can be misleading, and how to fix it. A practitioner's guide from the canonical 2×2 DiD to cohort-time ATTs, with full R implementation.\"\ndate: 2026-06-08\ncategories: [causal inference, econometrics, difference-in-differences, R]\n#draft: true\n---\n\n\n\n## The CEO's Dilemma: Was It Really You?\n\nYour company just completed a phased rollout of a new pricing algorithm. Deployed to the Northeast in Q1, the Midwest in Q2, and the South in Q3. Internal analytics reports a **4.8% improvement in gross margin**. The board is pleased. The CFO wants to accelerate the next initiative.\n\nBefore you sign the budget: **did your algorithm cause that improvement?**\n\nYour VP of Data ran the standard two-way fixed effects regression. The coefficient is 4.8%, p-value < 0.01. Looks solid. But here is the uncomfortable truth that even many sophisticated analytics teams do not know: in a staggered rollout design like this one, that regression may not be estimating a policy-relevant average treatment effect. It is estimating a non-transparent weighted average of pairwise comparisons, driven by group sizes, treatment timing variance, and residual variation in treatment, some of which are economically nonsensical, some of which receive negative weights, and none of which corresponds to any question a rational business leader would want answered.\n\nThis is not a hypothetical risk. Goodman-Bacon (2021) demonstrated that TWFE estimates in staggered settings can be negative even when the true treatment effect is positive for every treated unit at every time period. This sign reversal occurs because already-treated units serve as implicit controls for later-treated units, and their treatment effects contaminate the comparison. The resulting bias can be large enough to reverse the sign, leading to materially incorrect strategic decisions, such as scaling back programmes that are working or expanding those that are not.\n\nThis article gives you the tools to get it right.\n\nBy the end you will understand:\n\n1. How classical DiD works and exactly when it stops working\n2. Why TWFE can fail under staggered adoption: the Goodman-Bacon decomposition in plain language\n3. How Callaway and Sant'Anna (2021) builds valid causal estimates from first principles\n4. The full menu of ATT aggregations and what business question each one answers\n5. A complete R implementation using real minimum-wage data from the `did` package\n\n---\n\n## Part I: Classical Difference-in-Differences {#part-i}\n\n### The Counterfactual Problem\n\nEvery causal question has the same structure: compare what *did* happen to what *would have happened* without the intervention. We observe the former but can never directly observe the latter. That unobserved alternative is the **counterfactual**, the fundamental object of causal inference.\n\nThe entire DiD toolkit is an answer to one question: *where do we find a credible proxy for the missing counterfactual?*\n\nDiD's answer is elegant: use a **control group's change over time** as an estimate of the counterfactual change for the treated group.\n\n### The 2×2 Setup\n\nThe canonical DiD design has four cells: two groups (treated, control) and two time periods (pre, post). The parameter of interest is the **average treatment effect on the treated** (ATT), and the estimator is:\n\n$$\\widehat{ATT} = \\underbrace{(\\bar{Y}^{T}_{post} - \\bar{Y}^{T}_{pre})}_{\\text{Change for treated}} - \\underbrace{(\\bar{Y}^{C}_{post} - \\bar{Y}^{C}_{pre})}_{\\text{Change for control}}$$\n\nThe first difference captures the total change for treated units. The second difference subtracts the change that would have occurred anyway due to common time trends. Together they isolate the treatment effect. Note that the ATT is the effect for the treated group specifically; it differs from the ATE (average treatment effect on the entire population) unless treatment is randomly assigned.\n\n**A concrete business example.** You raise prices in Portugal but not in Spain. You want the causal impact on monthly churn:\n\n| Group | Pre-Increase | Post-Increase | Change |\n|:------|:------------:|:--------------:|:------:|\n| Portugal (Treated) | 2.5% | 3.8% | +1.3pp |\n| Spain (Control)    | 2.3% | 2.6% | +0.3pp |\n| **DiD Estimate (ATT)** | | | **+1.0pp** |\n\nThe price increase *caused* an estimated 1.0 percentage-point rise in churn, after netting out the common macro trend affecting both markets. This is the ATT: the average effect on the market that actually received the treatment.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\n\n# Canonical DiD data\ndid_data <- tibble(\n  period = c(\"Pre\", \"Pre\", \"Post\", \"Post\"),\n  group  = c(\"Portugal (Treated)\", \"Spain (Control)\",\n             \"Portugal (Treated)\", \"Spain (Control)\"),\n  churn  = c(2.5, 2.3, 3.8, 2.6)\n)\n\n# Counterfactual: Portugal following Spain's trend\ncf <- tibble(\n  period = c(\"Pre\", \"Post\"),\n  group  = c(\"Portugal (Counterfactual)\", \"Portugal (Counterfactual)\"),\n  churn  = c(2.5, 2.5 + (2.6 - 2.3))  # Portugal pre + Spain's change\n)\n\nplot_data <- bind_rows(did_data, cf) %>%\n  mutate(\n    period = factor(period, levels = c(\"Pre\", \"Post\")),\n    ltype  = ifelse(group == \"Portugal (Counterfactual)\", \"dashed\", \"solid\"),\n    colour = case_when(\n      group == \"Portugal (Treated)\"      ~ \"#E74C3C\",\n      group == \"Spain (Control)\"         ~ \"#3498DB\",\n      group == \"Portugal (Counterfactual)\" ~ \"#E74C3C\"\n    )\n  )\n\nggplot(plot_data, aes(x = period, y = churn, group = group,\n                      colour = colour, linetype = ltype)) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 3) +\n  annotate(\"segment\",\n           x = 2, xend = 2,\n           y = cf$churn[2], yend = 3.8,\n           arrow = arrow(ends = \"both\", length = unit(0.15, \"cm\")),\n           colour = \"#2C3E50\", linewidth = 0.8, linetype = \"solid\") +\n  annotate(\"label\", x = 2.05, y = (3.8 + cf$churn[2]) / 2,\n           label = \"ATT = +1.0pp\", hjust = 0,\n           colour = \"#2C3E50\", size = 3.5, fontface = \"bold\") +\n  scale_colour_identity() +\n  scale_linetype_identity() +\n  scale_y_continuous(labels = scales::label_number(suffix = \"%\")) +\n  labs(\n    title    = \"The Canonical DiD: Price Increase and Churn\",\n    subtitle = \"The counterfactual (dashed) is built from Spain's observed trend\",\n    x = NULL, y = \"Monthly Churn Rate\",\n    caption  = \"Treated: Portugal | Control: Spain\"\n  ) +\n  annotate(\"text\", x = 1.05, y = 2.5,\n           label = \"Portugal (Treated)\", colour = \"#E74C3C\",\n           fontface = \"bold\", hjust = 0, size = 3) +\n  annotate(\"text\", x = 1.05, y = 2.17,\n           label = \"Spain (Control)\", colour = \"#3498DB\",\n           fontface = \"bold\", hjust = 0, size = 3) +\n  annotate(\"text\", x = 2.05, y = 2.72,\n           label = \"Counterfactual\", colour = \"#E74C3C\",\n           hjust = 0, size = 3, fontface = \"italic\") +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"none\",\n        panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![The canonical 2×2 DiD. Portugal's counterfactual (dashed) is constructed from Spain's trend. The ATT is the gap between observed and counterfactual outcomes after treatment.](did_for_ceos_files/figure-html/canonical-did-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### The Parallel Trends Assumption\n\nThe DiD estimate is only valid under one critical assumption:\n\n> **Parallel Trends**: In the absence of treatment, the average outcomes for treated and control groups would have followed the same trajectory over time.\n\nFormally, denoting $Y_t(0)$ as the untreated potential outcome:\n\n$$\\mathbb{E}[Y_t(0) - Y_{t-1}(0) \\mid D = 1] = \\mathbb{E}[Y_t(0) - Y_{t-1}(0) \\mid D = 0]$$\n\nThis assumption is untestable in the post-treatment period: we never observe $Y_t(0)$ for treated units after treatment. What we *can* do is inspect pre-treatment trends as supporting evidence. If the groups were on parallel paths before treatment, it is more credible (though not certain) that they would have remained so.\n\n::: {.callout-important}\n**The Parallel Trends assumption does not require the groups to have the same outcome *levels*, only the same *trend*.**  \nIt is a statement about what would have happened in a counterfactual world, not about what we actually observe.\n:::\n\n### Estimation via TWFE: Why It Works in 2×2\n\nIn the canonical setting, the DiD estimate is identical to the coefficient $\\hat{\\beta}^{TWFE}$ from this regression:\n\n$$Y_{it} = \\alpha_i + \\lambda_t + \\beta^{TWFE} D_{it} + \\varepsilon_{it}$$\n\nwhere $\\alpha_i$ are unit fixed effects, $\\lambda_t$ are time fixed effects, and $D_{it} \\in \\{0,1\\}$ is the treatment indicator (equal to 1 when unit $i$ is treated at time $t$, 0 otherwise). The unit FEs absorb time-invariant group differences; the time FEs absorb common shocks; $\\beta^{TWFE}$ captures the residual, which is exactly the DiD estimate.\n\nIn a 2×2 design, TWFE is equivalent to DiD. This is the source of its appeal, and the source of a dangerous false confidence when applied to more complex settings.\n\n---\n\n## Part II: The Staggered Adoption Problem {#part-ii}\n\n### What Is Staggered Adoption?\n\nReal business rollouts rarely follow the tidy 2×2 pattern. The following are representative examples:\n\n| Business Context | Staggered Pattern |\n|:----------------|:-----------------|\n| Software feature rollout | Wave 1: Premium customers (Jan); Wave 2: Mid-market (Apr); Wave 3: SMB (Jul) |\n| New store format | Pilot: 20 stores (2022); Expansion: 80 stores (2023); Full: 200 stores (2024) |\n| Minimum wage increase | States adopt at different years (2015 through 2022) |\n| Marketing automation | Deployed by region as infrastructure is ready |\n| Pricing algorithm | Rolled out market-by-market over 12 months |\n\nThis is **staggered treatment adoption**: different units (regions, stores, customers, states) receive treatment at different calendar times. For decades, the standard practice was simply to run TWFE on the full panel and interpret the coefficient as the average treatment effect. That coefficient can be misleading when treatment effects vary across cohorts or over time.\n\n### The Goodman-Bacon Decomposition Theorem\n\nGoodman-Bacon (2021) delivered the definitive diagnosis. He proved that in a staggered design, the TWFE estimator is a variance-weighted average of all possible 2×2 DiD comparisons that can be formed from the data.\n\nWith $K$ timing cohorts, this produces $O(K^2)$ pairwise comparisons. Some are economically valid. Others are contaminated.\n\n\n```{mermaid}\n%%{init: {'theme':'base','themeVariables':{'primaryColor':'#EBF5FB','edgeLabelBackground':'#fff','fontSize':'14px'}}}%%\nflowchart TD\n    A[\"TWFE coefficient β̂\"] --> B[\"Variance-weighted average of all<br/> pairwise 2×2 DiDs\"]\n    B --> C[\"Type 1 <br/> Early-treated vs Never-treated<br/>✅ Clean\"]\n    B --> D[\"Type 2 <br/> Late-treated vs Never-treated<br/>✅ Clean\"]\n    B --> E[\"Type 3 <br/> Late-treated vs Early-treated<br/>❌ Contaminated\"]\n    C --> F[\"Valid comparison<br/>Receives positive weight under standard decomposition\"]\n    D --> G[\"Valid comparison<br/>Receives positive weight under standard decomposition\"]\n    E --> H[\"Already-treated units used as controls <br/> Outcomes contaminated by their own treatment effect <br/> Weights can be negative (non-convex averaging)\"]\n\n    style E fill:#FADBD8,stroke:#E74C3C\n    style H fill:#FADBD8,stroke:#E74C3C\n    style C fill:#D5F5E3,stroke:#27AE60\n    style D fill:#D5F5E3,stroke:#27AE60\n    style F fill:#D5F5E3,stroke:#27AE60\n    style G fill:#D5F5E3,stroke:#27AE60\n```\n\n**The contaminated comparison.** Suppose Cohort A is treated at $t=2$ and Cohort B is treated at $t=4$. TWFE forms a comparison where Cohort B is the \"treated\" unit and Cohort A (already treated) serves as the \"control\" during periods 3 and 4. But Cohort A's outcomes in those periods include Cohort A's own treatment effect. If treatment effects vary across cohorts or over time, this comparison is contaminated and its contribution to the TWFE estimate can receive negative weight.\n\n### The Negative Weights Problem: A Numerical Example\n\nLet us make this concrete. Imagine three cohorts:\n\n- **Cohort E** (Early): treated at $t=2$, with treatment effects that grow over time (ATT = 1 at $t=2$, 3 at $t=3$, 5 at $t=4$, 7 at $t=5$)\n- **Cohort L** (Late): treated at $t=4$, with ATT = 1 at $t=4$, 3 at $t=5$\n- **Cohort N**: never treated\n\nEvery true treatment effect is positive. But the Goodman-Bacon decomposition reveals two distinct problems in this setting. First, TWFE forms a Late-vs-Early comparison that uses Cohort E's outcomes (already contaminated by its own treatment effect) as the counterfactual for Cohort L, a substantively invalid comparison. Second, because Cohort E's treatment effects grow over time (it has been treated longer), this contaminated comparison can receive negative weight in the variance-weighted TWFE average. Depending on group sizes and timing, the overall TWFE coefficient can be biased downward or even negative.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(ggplot2)\nlibrary(tidyr)\n\nset.seed(42)\nn_per_group <- 100\nperiods     <- 1:6\n\n# Draw unit fixed effects at the unit level first, then expand\nn_units <- 3 * n_per_group\nunit_ids <- 1:n_units\nunit_fes <- rnorm(n_units, sd = 1)\n\n# True ATTs grow with exposure: ATT(e) = e + 1\nsim_df <- expand.grid(id = unit_ids, t = periods) %>%\n  as_tibble() %>%\n  arrange(id, t) %>%\n  mutate(\n    group = case_when(\n      id <= n_per_group               ~ \"Early (g=2)\",\n      id <= 2 * n_per_group           ~ \"Late (g=4)\",\n      TRUE                            ~ \"Never Treated\"\n    ),\n    first_treat = case_when(\n      group == \"Early (g=2)\"  ~ 2,\n      group == \"Late (g=4)\"   ~ 4,\n      TRUE                    ~ Inf\n    ),\n    # Unit FE: same value for all time periods of the same unit\n    unit_fe     = unit_fes[id],\n    Y0          = 5 + unit_fe + 0.5 * t + rnorm(n(), sd = 0.5),\n    # Treated potential outcome: ATT = e + 1 (e = event time, exposure duration)\n    e           = ifelse(is.finite(first_treat), t - first_treat, -Inf),\n    Y1          = Y0 + ifelse(e >= 0, e + 1, 0),\n    D           = as.integer(t >= first_treat & is.finite(first_treat)),\n    Y           = ifelse(D == 1, Y1, Y0)\n  )\n\n# Compute group means\nmeans_df <- sim_df %>%\n  group_by(group, t) %>%\n  summarise(Y_mean = mean(Y), .groups = \"drop\")\n\nggplot(means_df, aes(x = t, y = Y_mean, colour = group, group = group)) +\n  geom_vline(xintercept = 2, linetype = \"dashed\", colour = \"#E74C3C\", alpha = 0.5) +\n  geom_vline(xintercept = 4, linetype = \"dashed\", colour = \"#E67E22\", alpha = 0.5) +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 3) +\n  annotate(\"label\", x = 2, y = 4.5, label = \"Early\\ntreated\", colour = \"#E74C3C\",\n           size = 3, fontface = \"bold\") +\n  annotate(\"label\", x = 4, y = 4.5, label = \"Late\\ntreated\", colour = \"#E67E22\",\n           size = 3, fontface = \"bold\") +\n  scale_colour_manual(values = c(\n    \"Early (g=2)\"  = \"#E74C3C\",\n    \"Late (g=4)\"   = \"#E67E22\",\n    \"Never Treated\" = \"#3498DB\"\n  )) +\n  labs(\n    title    = \"Staggered Adoption: True Effects Are Positive Everywhere\",\n    subtitle = \"TWFE uses the already-treated Early cohort as 'control' for the Late cohort\",\n    x = \"Time Period\", y = \"Mean Outcome Y\",\n    colour = \"Group\",\n    caption = \"Simulated data. True ATT(e) = e + 1 for all cohorts.\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"bottom\",\n        panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Simulated staggered adoption: every true ATT is positive, yet TWFE produces a downward-biased estimate in this configuration due to the contaminated comparison between early-treated (used as control) and late-treated cohorts. The direction and magnitude of bias depend on group sizes, timing, and the specific pattern of effect heterogeneity.](did_for_ceos_files/figure-html/negative-weights-sim-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### TWFE vs the Truth: A Direct Comparison\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nlibrary(fixest)\n\n# Estimate TWFE on simulated data\ntwfe_model <- feols(Y ~ D | id + t, data = sim_df, cluster = ~id)\ntwfe_est   <- coef(twfe_model)[\"D\"]\n\n# True ATT: average over all post-treatment cohort-time cells\ntrue_att <- sim_df %>%\n  filter(D == 1) %>%\n  summarise(true_att = mean(Y1 - Y0)) %>%\n  pull(true_att)\n\ncomparison <- tibble(\n  Method  = c(\"True ATT\", \"TWFE Estimate\"),\n  Estimate = c(true_att, twfe_est),\n  Note     = c(\"What we want to know\", \"What TWFE actually estimates\")\n)\n\nggplot(comparison, aes(x = Method, y = Estimate, fill = Method)) +\n  geom_col(width = 0.5, colour = \"white\") +\n  geom_text(aes(label = sprintf(\"%.2f\", Estimate)),\n            vjust = -0.5, fontface = \"bold\", size = 4.5) +\n  geom_hline(yintercept = 0, colour = \"black\") +\n  scale_fill_manual(values = c(\"True ATT\" = \"#27AE60\", \"TWFE Estimate\" = \"#E74C3C\")) +\n  labs(\n    title    = \"True ATT vs TWFE Estimate Under Staggered Adoption\",\n    subtitle = \"Every unit has a positive treatment effect, yet TWFE underestimates the truth\",\n    y = \"Estimated Effect\", x = NULL,\n    caption  = \"Simulated data with dynamic treatment effects (ATT grows with exposure)\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"none\",\n        panel.grid.minor = element_blank(),\n        panel.grid.major.x = element_blank())\n```\n\n::: {.cell-output-display}\n![When true effects are heterogeneous, TWFE produces a distorted, variance-weighted average. With staggered adoption, the bias is systematic and can reverse the sign.](did_for_ceos_files/figure-html/twfe-vs-truth-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\nThe practical implications for business leaders are severe:\n\n| Scenario | TWFE Bias | Likely Consequence |\n|:--------|:----------|:------------------|\n| Effects grow with exposure | Underestimates true effect | May lead to scaling back a programme still building impact |\n| Effects fade over time | Overestimates long-run impact | May lead to over-investing past the programme's effective horizon |\n| Early adopters respond more strongly | Distorts cohort comparison | Misallocate budget across markets |\n| Treatment effects are homogeneous across cohorts and time | No bias from decomposition; no anticipation and parallel trends still required | TWFE remains valid in this special case |\n\n---\n\n## Part III: The Callaway–Sant'Anna Framework {#part-iii}\n\n### A Different Philosophy: Forward Engineering\n\nThe TWFE approach runs a convenient regression and tries to interpret its coefficient. Callaway and Sant'Anna (2021) take the opposite approach: start by defining the parameter you actually want to estimate, then derive the estimator.\n\nThis \"forward engineering\" philosophy has three pillars:\n\n```{mermaid}\n%%{init: {'theme':'base','themeVariables':{'primaryColor':'#EBF5FB'}}}%%\nflowchart LR\n    A1[\"1. DISAGGREGATE<br/>Estimate ATT(g,t)<br/>for each<br/>cohort × calendar<br/>time cell\"]\n    -->\n    B1[\"2. CLEAN COMPARISONS<br/>Use only never-treated<br/>or not-yet-treated<br/>as controls<br/>(never already-treated)\"]\n    -->\n    C1[\"3. TRANSPARENT AGGREGATION<br/>Combine ATT(g,t)<br/>into summaries<br/>chosen by the researcher,<br/>not by OLS variance<br/>weights\"]\n\n    style A1 fill:#D6EAF8,stroke:#2980B9,stroke-width:2px,color:#000\n    style B1 fill:#D5F5E3,stroke:#27AE60,stroke-width:2px,color:#000\n    style C1 fill:#FDEBD0,stroke:#E67E22,stroke-width:2px,color:#000\n```\n\n### The Cohort-Time ATT: The Fundamental Building Block\n\nThroughout this article, we use **cohort** to refer to the set of units that first receive treatment in the same calendar period $g$. Let $G$ denote the random variable indicating the period in which a unit first receives treatment ($G = \\infty$ for never-treated units). The CS literature also calls these \"groups\"; we use \"cohort\" for clarity but the terms are equivalent.\n\nThe unit of analysis in the CS framework is the cohort-time average treatment effect:\n\n$$ATT(g,t) = \\mathbb{E}[Y_t(g) - Y_t(0) \\mid G = g]$$\n\nwhere:\n\n- $g$ = the calendar time when a cohort **first** becomes treated (the \"cohort\")\n- $t$ = the calendar time at which we evaluate the effect\n- $Y_t(g)$ = potential outcome at time $t$ for a unit first treated at $g$\n- $Y_t(0)$ = counterfactual potential outcome without treatment\n\nThis formulation assumes an **absorbing treatment**: once treated at time $g$, a unit remains treated in all subsequent periods. If treatment can be reversed or repeatedly switched, the standard CS framework does not directly apply; see de Chaisemartin & D'Haultfœuille (2020) for that case.\n\nEach $ATT(g,t)$ is directly interpretable: *\"What was the average effect of treatment, at calendar time $t$, for the cohort that began treatment at time $g$?\"*\n\nNo negative weights. No contaminated comparisons. No ambiguity about what the estimate means.\n\n::: {.callout-note}\n**The ATT(g,t) matrix.** Think of it as a grid with treatment cohorts on rows ($g$) and calendar time on columns ($t$). Pre-treatment cells ($t < g$) serve as parallel trends diagnostics; they should be near zero. Post-treatment cells ($t \\geq g$) are the causal parameters of interest.\n:::\n\n### Identification Assumptions\n\n**Assumption 1: No Anticipation**\n\nUnits do not change behaviour in anticipation of future treatment. Formally, for $t < g$:\n\n$$\\mathbb{E}[Y_t(g) \\mid G = g] = \\mathbb{E}[Y_t(0) \\mid G = g]$$\n\nIn business contexts: companies should not change behaviour before a new pricing algorithm goes live in ways that would shift the outcome variable. If significant anticipation occurs (e.g., inventory pre-loading before a cost-optimisation rollout), $ATT(g,t)$ captures the effect relative to already-adjusted baselines, which is a different parameter than the pure treatment effect. In such cases, redefine $g$ to the period when anticipation begins, or interpret the estimate accordingly.\n\n**Assumption 2: Conditional Parallel Trends**\n\nConditional on pre-treatment covariates $X$, the trend in untreated potential outcomes for cohort $g$ matches the trend for the comparison group (never-treated or not-yet-treated). All comparisons are anchored at the **last pre-treatment period $g-1$** for cohort $g$:\n\n$$\\mathbb{E}[Y_t(0) - Y_{g-1}(0) \\mid X, G = g] = \\mathbb{E}[Y_t(0) - Y_{g-1}(0) \\mid X, \\text{comparison}]$$\n\nThe conditioning on $X$ is a key advantage: if treated and control cohorts differ in observable characteristics that drive outcome trends, unconditional parallel trends fails, but conditional parallel trends may still hold. This expands the range of settings where DiD is credible.\n\n**Comparison group choices:**\n\n| Choice | Comparison Units | When to Prefer |\n|:-------|:----------------|:--------------|\n| `nevertreated` | Units that are never treated | When a clean, stable comparison group exists |\n| `notyettreated` | Units not yet treated by time $t$ | When all units eventually get treated; larger comparison group |\n\n**Assumption 3: Overlap**\n\nFor each covariate profile, there are both treated and comparison units: $0 < P(G = g \\mid X) < 1$. Without overlap, the counterfactual cannot be constructed for some units without extrapolation.\n\n### Doubly Robust Estimation\n\nThe CS framework offers three estimators. The recommended default is **doubly robust (DR)**:\n\n| Estimator | Models Required | Consistent If |\n|:----------|:---------------|:-------------|\n| Outcome Regression (OR) | Outcome model for comparison group | Outcome model correctly specified |\n| Inverse Probability Weighting (IPW) | Propensity score $P(G=g \\mid X)$ | Propensity score correctly specified |\n| **Doubly Robust (DR)** | Both outcome model + propensity score | **Either** model correctly specified |\n\nThe DR estimator combines inverse-probability weighting and outcome regression via a doubly robust score. Using the notation of Sant'Anna & Zhao (2020), where $G_g = \\mathbf{1}\\{G = g\\}$ is the cohort indicator and $C$ is the comparison-group indicator:\n\n$$\\widehat{ATT}^{DR}(g,t) = \\mathbb{E}\\left[\\left(\\frac{G_g}{\\mathbb{E}[G_g]} - \\frac{\\hat{p}_g(X) \\cdot C}{(1-\\hat{p}_g(X))\\,\\mathbb{E}\\!\\left[\\frac{\\hat{p}_g(X)\\, C}{1-\\hat{p}_g(X)}\\right]}\\right)\\!\\!\\left(Y_t - Y_{g-1} - \\hat{m}_{g,t}(X)\\right)\\right]$$\n\nwhere $\\hat{p}_g(X) = \\hat{P}(G = g \\mid X,\\, G_g + C = 1)$ is the estimated propensity score and $\\hat{m}_{g,t}(X)$ is the estimated conditional mean of $(Y_t - Y_{g-1})$ for the comparison group. See Sant'Anna & Zhao (2020, eq. 3.1) for the full formal derivation.\n\n::: {.callout-tip}\n**For business practitioners.** The doubly robust property means: if your data scientists get either the outcome model *or* the propensity score model wrong (but not both), the estimate is still consistent. This is a substantial robustness advantage when you cannot fully verify functional form assumptions, which is almost always the case.\n:::\n\n---\n\n\n## Part IV: Aggregating ATT(g,t) into Business Answers {#part-iv}\n\nA study with 5 treatment cohorts and 10 post-treatment periods produces 50 $ATT(g,t)$ estimates. The richness is a feature (heterogeneity is real and important), but leadership and policy audiences need summary parameters. The CS framework provides four aggregation schemes via `aggte()`, each answering a fundamentally different substantive question. All share the general form:\n\n$$\\theta = \\sum_{g \\in \\mathcal{G}} \\sum_{\\substack{t \\geq g \\\\ t \\leq T}} w(g,t) \\cdot ATT(g,t)$$\n\nThe weighting functions $w(g,t)$ are the essential difference between aggregators: they determine *whose* treatment effect gets prioritised and along *which* dimension heterogeneity is summarised.\n\n```{mermaid}\n%%{init: {'theme':'base','themeVariables':{'primaryColor':'#F8F9FA'}}}%%\nflowchart TD\n    A[\"ATT(g,t) Matrix <br/> (all cohort × time cells)\"] --> B[\"Simple Overall ATT <br/> 'Did the programme work on average?'\"]\n    A --> C[\"Event-Study ATT θ(e) <br/> 'How does the effect evolve with exposure?'\"]\n    A --> D[\"Cohort-Specific ATT θ(g) <br/> 'Did early adopters do better?'\"]\n    A --> E[\"Calendar-Time ATT θ(t)<br/>'What was the total impact in Q3?'\"]\n\n    style A fill:#2C3E50,color:white\n    style B fill:#D5F5E3,stroke:#27AE60\n    style C fill:#D6EAF8,stroke:#2980B9\n    style D fill:#FDEBD0,stroke:#E67E22\n    style E fill:#FADBD8,stroke:#E74C3C\n```\n\n---\n\n### Aggregation 1: Event-Study / Dynamic Effects (`type = \"dynamic\"`)\n\n$$\\theta_{ES}(e) = \\sum_{g \\in \\mathcal{G}} \\mathbf{1}\\{g + e \\leq T\\} \\cdot P(G = g \\mid G + e \\leq T) \\cdot ATT(g,\\, g+e)$$\n\nwhere $e = t - g$ is **event time**: the number of periods elapsed since a unit's cohort first received treatment. This converts calendar time into a common scale of exposure duration.\n\n**Business question:** *\"How does the treatment effect evolve as exposure duration increases?\"*\n\nThis is the most informative aggregation for strategic questions about programme dynamics:\n\n- **$e < 0$**: Pre-treatment pseudo-effects. Under correct identification these should be statistically indistinguishable from zero, serving as a falsification test for parallel trends.\n- **$e = 0$**: The immediate impact on the first period of treatment adoption.\n- **$e > 0$**: Dynamic build-up, saturation, or decay of the causal effect over time.\n\n**Example:** A new HR wellness programme has $\\theta_{ES}(0) = 0.5\\%$ reduction in absenteeism, growing to $\\theta_{ES}(4) = 2.1\\%$ by the end of the first year. The event study captures this learning curve that a single TWFE coefficient would obscure entirely.\n\n```r\nagg.es <- aggte(example_attgt, type = \"dynamic\")\nsummary(agg.es)\n```\n\n```\nOverall summary of ATT's based on event-study / dynamic aggregation:\n     ATT    Std. Error  [95% Conf. Int.]\n  1.9904    0.0375      1.9169  2.0639  *\n\nDynamic Effects:\n  Event time  Estimate  Std. Error  [95% Simult. Conf. Band]\n  -2           0.0023    0.0705     -0.1777   0.1824\n  -1           0.0105    0.0409     -0.0939   0.1149\n   0           0.9929    0.0319      0.9115   1.0742  *\n   1           2.0231    0.0477      1.9013   2.1450  *\n   2           2.9552    0.0622      2.7964   3.1141  *\n```\n\n| $e$ | Phase | Estimate | Interpretation |\n|:----|:------|:---------|:---------------|\n| $-2$ | Pre-treatment | $0.002\\ [-0.18;\\, 0.18]$ | Null effect; consistent with parallel trends |\n| $-1$ | Pre-treatment | $0.011\\ [-0.09;\\, 0.11]$ | Additional support for the identifying assumption |\n| $0$ | Immediate impact | $0.993\\ [0.91;\\, 1.07]^*$ | Average effect at the moment of adoption |\n| $1$ | 1 period after | $2.023\\ [1.90;\\, 2.15]^*$ | Effect doubles: treatment maturation |\n| $2$ | 2 periods after | $2.955\\ [2.80;\\, 3.11]^*$ | Effect nearly triples: growing pattern |\n\n: Interpreting the Dynamic Effects {.striped}\n\n::: {.callout-note}\n**Overall ATT in event-study aggregation.** The Overall ATT of 1.99 reported by `aggte(type = \"dynamic\")` is a weighted average of $\\theta_{ES}(e)$ across post-treatment event times, weighted by cohort size. It should not be interpreted as the primary global causal effect, because it conflates exposure duration with cohort composition: cohorts that happen to be observed for more post-treatment periods receive more weight. For a clean global summary that weights each cohort equally regardless of observation length, prefer `aggte(type = \"group\")`, its overall ATT is the leading recommendation of Callaway & Sant'Anna (2021).\n:::\n\n::: {.callout-warning}\n**Dynamic cohort composition.** For different values of $e$, the set of cohorts contributing to $\\theta_{ES}(e)$ changes: earlier-treated cohorts contribute to more event-time estimates than later cohorts. **Critically, the trajectory of $\\theta_{ES}(e)$ can confound genuine dynamics with cohort-level heterogeneity**: if early-treated cohorts have systematically different treatment effects than later cohorts, the event-study plot reflects both exposure-length effects and compositional shifts across cohorts. This contamination disappears only when cohort effects are absent. Use `balance_e = k` to restrict estimation to cohorts observed for at least $k$ post-treatment periods, which holds composition constant:\n\n```r\nagg.es.bal <- aggte(example_attgt, type = \"dynamic\", balance_e = 2)\nsummary(agg.es.bal)\n```\n:::\n\n---\n\n### Aggregation 2: Cohort-Specific Effects (`type = \"group\"`)\n\n$$\\theta^{group}(g) = \\frac{1}{T - g + 1} \\sum_{t \\geq g} ATT(g,\\, t)$$\n\nEach cohort-specific $\\theta^{group}(g)$ is the simple average of $ATT(g,t)$ across all post-treatment periods for that cohort. The overall ATT is then the cohort-size-weighted average:\n\n$$\\theta^{group}_{overall} = \\sum_{g \\in \\mathcal{G}} \\theta^{group}(g) \\cdot P(G = g \\mid G \\leq T)$$\n\n**Business question:** *\"Did early-adopting cohorts experience larger (or smaller) effects than later adopters?\"*\n\nA key property: each cohort receives exactly one weight in the global average, regardless of how many post-treatment periods it has been observed. This avoids the systematic over-weighting of early-treated cohorts that afflicts TWFE and the `simple` aggregator.\n\n```r\nagg.gs <- aggte(example_attgt, type = \"group\")\nsummary(agg.gs)\n```\n\n```\nOverall summary of ATT's based on group / cohort aggregation:\n     ATT    Std. Error  [95% Conf. Int.]\n  1.488    0.0343      1.4208  1.5553  *\n\nGroup Effects:\n  Group  Estimate  Std. Error  [95% Simult. Conf. Band]\n  2      1.9545    0.0520      1.8298   2.0793  *\n  3      1.5835    0.0562      1.4488   1.7183  *\n  4      0.9523    0.0649      0.7968   1.1078  *\n```\n\nThe descending pattern $\\hat\\theta^{group}(g{=}2) > \\hat\\theta^{group}(g{=}3) > \\hat\\theta^{group}(g{=}4)$ is substantively relevant and admits multiple explanations:\n\n- **Accumulated exposure**: Early cohorts have been treated longer, allowing effects to compound.\n- **Selection**: Units that adopt earlier may be systematically different (higher motivation, better resources, more favourable context).\n- **Macro-institutional context**: The economic or regulatory environment may have shifted between adoption waves, affecting treatment efficacy.\n\n::: {.callout-tip}\n**Authors' Recommendation (Callaway & Sant'Anna, 2021).** The `type = \"group\"` aggregator is the leading choice as the primary measure of global effect. The Overall ATT of **1.488** represents the average effect of participating in the treatment for a typical treated unit, directly analogous to the ATT in the canonical two-period, two-group design, and the most internally coherent summary statistic in staggered settings.\n:::\n\n---\n\n### Aggregation 3: Calendar-Time Effects (`type = \"calendar\"`)\n\n$$\\theta^{cal}(t) = \\sum_{g \\in \\mathcal{G}} \\mathbf{1}\\{t \\geq g\\} \\cdot P(G = g \\mid G \\leq t) \\cdot ATT(g,\\, t)$$\n\n**Business question:** *\"What was the aggregate impact of the programme in fiscal quarter $t$?\"*\n\nThis aggregator maps directly to financial and operational reporting: *\"In Q3 2024, the algorithm generated X% margin improvement across all deployed markets.\"*\n\n```r\nagg.ct <- aggte(example_attgt, type = \"calendar\")\nsummary(agg.ct)\n```\n\n```\nOverall summary of ATT's based on calendar time aggregation:\n     ATT    Std. Error  [95% Conf. Int.]\n  1.4808    0.0347      1.4128  1.5488  *\n\nTime Effects:\n  Time  Estimate  Std. Error  [95% Simult. Conf. Band]\n  2     0.9209    0.0632      0.7722   1.0697  *\n  3     1.5491    0.0496      1.4324   1.6659  *\n  4     1.9724    0.0500      1.8547   2.0901  *\n```\n\n| $t$ | Contributing Cohorts | Interpretation |\n|:----|:---------------------|:---------------|\n| $t=2$ | Only $g=2$ (1st year) | Initial effect, only the earliest cohort contributes |\n| $t=3$ | $g=2$ (2nd year) + $g=3$ (1st year) | Combines cohort 2 maturation with cohort 3 entry |\n| $t=4$ | $g=2$, $g=3$, and $g=4$ | All cohorts contribute, maximum aggregate effect |\n\n: Interpreting the Calendar-Time Effects {.striped}\n\nThis aggregator is particularly useful for evaluating the policy's impact in specific fiscal years or for understanding how the aggregate effect evolves as more units receive treatment.\n\n---\n\n### Aggregation 4: Simple ATT (`type = \"simple\"`)\n\n$$\\theta^{simple} = \\frac{1}{\\kappa} \\sum_{g \\in \\mathcal{G}} \\sum_{t \\geq g} ATT(g,t) \\cdot P(G = g \\mid G \\leq T)$$\n\nwhere $\\kappa = \\sum_{g \\in \\mathcal{G}} \\sum_{t \\geq g} P(G = g \\mid G \\leq T)$ normalises the weights. Each $ATT(g,t)$ cell receives a weight proportional to the cohort's share among ever-treated units times the number of post-treatment periods that cohort contributes, which is why earlier-treated cohorts accumulate more weight.\n\n```\nATT     Std. Error  [95% Conf. Int.]\n1.6583  0.0333      1.5931  1.7236  *\n```\n\n::: {.callout-warning}\n**Limitation of the `simple` aggregator.** `type = \"simple\"` systematically over-weights early-treated cohorts, because they contribute more post-treatment $(g, t)$ cells and therefore accumulate more weight. This is related to the pathological weighting of TWFE in staggered designs (though the mechanism differs: TWFE uses variance weights while the simple aggregator uses cell-count weights). Use this aggregator only for benchmarking against TWFE or for exploratory sensitivity analysis. It should never be the primary summary of the global treatment effect.\n:::\n\n---\n\n### The Aggregation Decision Matrix\n\n| Business Question | Aggregation | `aggte(type=...)` | Role |\n|:-----------------|:------------|:------------------|:-----|\n| \"What was the average effect for a typical treated unit?\" | Cohort-specific | `\"group\"` | Primary |\n| \"When did effects kick in and how did they evolve?\" | Event Study | `\"dynamic\"` | Complementary |\n| \"What was the total impact in fiscal year $t$?\" | Calendar-time | `\"calendar\"` | Complementary |\n| \"How does this compare to a naive TWFE estimate?\" | Simple | `\"simple\"` | Sensitivity only |\n\n---\n\n## Part V: Full R Implementation with Minimum Wage Data {#part-v}\n\nThe `did` package ships with county-level employment data from Callaway and Sant'Anna (2021). Several US states increased their minimum wages at different points in time, creating a classic staggered adoption design. This section walks through a complete end-to-end implementation: data preparation, estimation of the $ATT(g,t)$ matrix, pre-trend testing, all four aggregations, and a head-to-head comparison with TWFE.\n\n### Data Preparation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# install.packages(c(\"did\", \"fixest\", \"ggplot2\", \"dplyr\", \"tidyr\",\n#                    \"scales\", \"patchwork\"))\n\nlibrary(did)\nlibrary(fixest)\nlibrary(ggplot2)\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(scales)\nlibrary(patchwork)\n\ndata(mpdta)\nglimpse(mpdta)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,500\nColumns: 6\n$ year        <int> 2003, 2004, 2005, 2006, 2007, 2003, 2004, 2005, 2006, 2007…\n$ countyreal  <dbl> 8001, 8001, 8001, 8001, 8001, 8019, 8019, 8019, 8019, 8019…\n$ lpop        <dbl> 5.896761, 5.896761, 5.896761, 5.896761, 5.896761, 2.232377…\n$ lemp        <dbl> 8.461469, 8.336870, 8.340217, 8.378161, 8.487352, 4.997212…\n$ first.treat <dbl> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007…\n$ treat       <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\nThe `mpdta` dataset contains the following variables:\n\n| Variable | Description |\n|:---------|:------------|\n| `lemp` | Log county-level teen employment (outcome) |\n| `year` | Calendar year (2003–2007) |\n| `countyreal` | County identifier |\n| `first.treat` | Year of first minimum wage increase (`0` = never treated) |\n| `treat` | `1` if county is treated in this year |\n\n: Variables in `mpdta` {.striped}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncat(\"Number of counties:\", n_distinct(mpdta$countyreal), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nNumber of counties: 500 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Years:\", paste(sort(unique(mpdta$year)), collapse = \", \"), \"\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nYears: 2003, 2004, 2005, 2006, 2007 \n```\n\n\n:::\n\n```{.r .cell-code}\ncat(\"Treatment cohorts:\\n\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTreatment cohorts:\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(mpdta$first.treat) |> print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n   0 2004 2006 2007 \n1545  100  200  655 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntrend_df <- mpdta |>\n  mutate(cohort = case_when(\n    first.treat == 0    ~ \"Never Treated\",\n    first.treat == 2004 ~ \"Treated 2004\",\n    first.treat == 2006 ~ \"Treated 2006\",\n    first.treat == 2007 ~ \"Treated 2007\"\n  )) |>\n  group_by(cohort, year) |>\n  summarise(lemp = mean(lemp), .groups = \"drop\")\n\nggplot(trend_df, aes(x = year, y = lemp, colour = cohort, group = cohort)) +\n  geom_vline(xintercept = c(2004, 2006, 2007),\n             linetype = \"dashed\", colour = \"grey70\") +\n  geom_line(linewidth = 1.2) +\n  geom_point(size = 3) +\n  scale_colour_manual(values = c(\n    \"Never Treated\" = \"#2C3E50\",\n    \"Treated 2004\"  = \"#E74C3C\",\n    \"Treated 2006\"  = \"#E67E22\",\n    \"Treated 2007\"  = \"#3498DB\"\n  )) +\n  labs(\n    title    = \"Raw Employment Trends by Treatment Cohort\",\n    subtitle = \"Dashed lines indicate first year of treatment for each cohort\",\n    x = \"Year\", y = \"Log Teen Employment\",\n    colour = \"Cohort\",\n    caption = \"Data: Callaway & Sant'Anna (2021), mpdta\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position = \"bottom\",\n        panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Employment trends by treatment cohort. Pre-treatment trends are broadly similar across groups, providing visual support for parallel trends.](did_for_ceos_files/figure-html/explore-data-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Step 1: Estimate Cohort-Time ATTs with `att_gt()`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# Verify that lpop covariate is present in the dataset\nif (!\"lpop\" %in% names(mpdta)) stop(\"Variable 'lpop' not found in mpdta. Check did package version.\")\n\ncs_results <- att_gt(\n  yname         = \"lemp\",\n  gname         = \"first.treat\",\n  idname        = \"countyreal\",\n  tname         = \"year\",\n  xformla       = ~ lpop,\n  data          = mpdta,\n  est_method    = \"dr\",           # Doubly Robust (recommended)\n  control_group = \"nevertreated\",\n  bstrap        = TRUE,\n  biters        = 1000,\n  print_details = FALSE\n)\n\nsummary(cs_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\natt_gt(yname = \"lemp\", tname = \"year\", idname = \"countyreal\", \n    gname = \"first.treat\", xformla = ~lpop, data = mpdta, control_group = \"nevertreated\", \n    bstrap = TRUE, biters = 1000, est_method = \"dr\", print_details = FALSE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\nGroup-Time Average Treatment Effects:\n Group Time ATT(g,t) Std. Error [95% Simult.  Conf. Band]  \n  2004 2004  -0.0145     0.0226       -0.0737      0.0446  \n  2004 2005  -0.0764     0.0292       -0.1529      0.0001  \n  2004 2006  -0.1404     0.0352       -0.2325     -0.0484 *\n  2004 2007  -0.1069     0.0343       -0.1966     -0.0172 *\n  2006 2004  -0.0005     0.0239       -0.0629      0.0620  \n  2006 2005  -0.0062     0.0179       -0.0530      0.0406  \n  2006 2006   0.0010     0.0199       -0.0512      0.0531  \n  2006 2007  -0.0413     0.0199       -0.0933      0.0107  \n  2007 2004   0.0267     0.0140       -0.0099      0.0634  \n  2007 2005  -0.0046     0.0163       -0.0473      0.0382  \n  2007 2006  -0.0284     0.0200       -0.0807      0.0238  \n  2007 2007  -0.0288     0.0169       -0.0731      0.0155  \n---\nSignif. codes: `*' confidence band does not cover 0\n\nP-value for pre-test of parallel trends assumption:  0.23267\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Doubly Robust\n```\n\n\n:::\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggdid(cs_results,\n      title  = \"Cohort-Time ATTs: ATT(g,t) for Each Cohort × Calendar Time\",\n      xlab   = \"Year\",\n      ylab   = \"ATT(g,t)\",\n      legend = TRUE) +\n  theme_minimal(base_size = 12) +\n  theme(legend.position = \"bottom\")\n```\n\n::: {.cell-output-display}\n![Cohort-time ATT matrix. Pre-treatment cells (event time < 0) test parallel trends, estimates should cluster near zero. Post-treatment cells reveal the causal effects for each cohort at each calendar time.](did_for_ceos_files/figure-html/plot-att-gt-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n::: {.callout-tip}\n**Reading the ATT(g,t) plot.** Each panel corresponds to a treatment cohort $g$. Within each panel, observations to the left of the treatment date (pre-treatment) should be near zero; systematic deviation is evidence against parallel trends. Observations to the right are the causal effect estimates at each post-treatment period.\n:::\n\n### Step 2: Pre-Testing Parallel Trends\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nes_results <- aggte(cs_results,\n                    type  = \"dynamic\",\n                    min_e = -3,\n                    max_e = 2,\n                    na.rm = TRUE)\n\nsummary(es_results)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs_results, type = \"dynamic\", min_e = -3, max_e = 2, \n    na.rm = TRUE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n\nOverall summary of ATT's based on event-study/dynamic aggregation:  \n     ATT    Std. Error     [ 95%  Conf. Int.]  \n -0.0715        0.0175    -0.1058     -0.0372 *\n\n\nDynamic Effects:\n Event time Estimate Std. Error [95% Simult.  Conf. Band]  \n         -3   0.0267     0.0140       -0.0092      0.0626  \n         -2  -0.0036     0.0126       -0.0359      0.0287  \n         -1  -0.0232     0.0146       -0.0607      0.0142  \n          0  -0.0211     0.0122       -0.0523      0.0102  \n          1  -0.0530     0.0165       -0.0954     -0.0106 *\n          2  -0.1404     0.0381       -0.2381     -0.0428 *\n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Doubly Robust\n```\n\n\n:::\n\n```{.r .cell-code}\nggdid(es_results,\n      title  = \"Event Study: Pre- and Post-Treatment Effects\",\n      xlab   = \"Event Time (t - g)\",\n      ylab   = \"Average Treatment Effect\",\n      legend = FALSE) +\n  geom_vline(xintercept = -0.5, linetype = \"dashed\", colour = \"#2C3E50\") +\n  annotate(\"label\", x = -0.5,\n           y = max(es_results$att.egt, na.rm = TRUE) * 0.9,\n           label = \"Treatment\\nBegins\", size = 3, fontface = \"bold\") +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Event study plot including pre-treatment periods. Pre-treatment coefficients should be statistically indistinguishable from zero if parallel trends holds.](did_for_ceos_files/figure-html/pretest-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n**Interpreting the pre-test.** Pre-treatment coefficients (event time $< 0$) should be near zero and not statistically significant. Systematic deviations indicate parallel trends violations. The simultaneous confidence bands adjust for multiple testing across all event times; this correction is critical for honest statistical inference, as pointwise bands would understate the uncertainty.\n\n::: {.callout-warning}\n**Roth (2022) caution.** A pre-test that passes does not *prove* parallel trends; it merely fails to *reject* it. The pre-test has limited statistical power, particularly in small samples. Moreover, using the pre-test as a decision rule, proceeding only when it passes, stopping when it fails, introduces post-selection bias: the estimates you publish are conditional on having passed the test, which distorts their sampling distribution (Roth 2022). Treat a passing pre-test as one piece of evidence alongside substantive institutional knowledge about why the comparison group provides a valid counterfactual, not as a guarantee.\n:::\n\n### Step 3: Event-Study Aggregation\n\nThe pre-test above already produced the dynamic aggregation. This step extends it with a dedicated visualisation focused on causal dynamics, using the same estimates (`es_results`) already computed in Step 2 but now emphasising the post-treatment trajectory rather than the pre-trend diagnostic.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggdid(es_results,\n      title  = \"Event Study: Dynamic Treatment Effects\",\n      xlab   = \"Periods Since Treatment (Event Time)\",\n      ylab   = expression(theta^{ES}(e)),\n      legend = FALSE) +\n  theme_minimal(base_size = 13) +\n  theme(panel.grid.minor = element_blank())\n```\n\n::: {.cell-output-display}\n![Event-study aggregation: average effect at each exposure length, aggregated across cohorts. Confidence bands are simultaneous, correcting for multiple testing across event times.](did_for_ceos_files/figure-html/event-study-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Step 4: Simple Overall ATT\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\noverall_att <- aggte(cs_results,\n                     type  = \"simple\",\n                     na.rm = TRUE)\nsummary(overall_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs_results, type = \"simple\", na.rm = TRUE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n     ATT    Std. Error     [ 95%  Conf. Int.]  \n -0.0418        0.0113     -0.064     -0.0196 *\n\n\n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Doubly Robust\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"\\nOverall ATT estimate: %.4f\\n\", overall_att$overall.att))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nOverall ATT estimate: -0.0418\n```\n\n\n:::\n\n```{.r .cell-code}\ncat(sprintf(\"95%% CI: [%.4f, %.4f]\\n\",\n            overall_att$overall.att - 1.96 * overall_att$overall.se,\n            overall_att$overall.att + 1.96 * overall_att$overall.se))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n95% CI: [-0.0640, -0.0196]\n```\n\n\n:::\n:::\n\n\n### Step 5: Cohort-Specific Effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ngroup_att <- aggte(cs_results,\n                   type  = \"group\",\n                   na.rm = TRUE)\n\nsummary(group_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs_results, type = \"group\", na.rm = TRUE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n\nOverall summary of ATT's based on group/cohort aggregation:  \n     ATT    Std. Error     [ 95%  Conf. Int.]  \n -0.0328        0.0113     -0.055     -0.0106 *\n\n\nGroup Effects:\n Group Estimate Std. Error [95% Simult.  Conf. Band]  \n  2004  -0.0846     0.0270       -0.1434     -0.0258 *\n  2006  -0.0202     0.0181       -0.0596      0.0193  \n  2007  -0.0288     0.0168       -0.0653      0.0078  \n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Doubly Robust\n```\n\n\n:::\n\n```{.r .cell-code}\nggdid(group_att,\n      title  = \"Cohort-Specific ATTs: Average Effect by Treatment Cohort\",\n      xlab   = \"Treatment Cohort (Year of First Treatment)\",\n      ylab   = expression(theta^{group}(g)),\n      legend = FALSE) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Cohort-specific ATTs reveal whether earlier or later treatment cohorts experienced different average effects. The descending pattern across cohorts warrants investigation of accumulated exposure, selection, or changing macro context.](did_for_ceos_files/figure-html/cohort-effects-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Step 6: Calendar-Time Effects\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ncalendar_att <- aggte(cs_results,\n                      type  = \"calendar\",\n                      na.rm = TRUE)\n\nsummary(calendar_att)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\naggte(MP = cs_results, type = \"calendar\", na.rm = TRUE)\n\nReference: Callaway, Brantly and Pedro H.C. Sant'Anna.  \"Difference-in-Differences with Multiple Time Periods.\" Journal of Econometrics, Vol. 225, No. 2, pp. 200-230, 2021. <https://doi.org/10.1016/j.jeconom.2020.12.001>, <https://arxiv.org/abs/1803.09015> \n\n\nOverall summary of ATT's based on calendar time aggregation:  \n     ATT    Std. Error     [ 95%  Conf. Int.]  \n -0.0442        0.0169    -0.0774      -0.011 *\n\n\nTime Effects:\n Time Estimate Std. Error [95% Simult.  Conf. Band]  \n 2004  -0.0145     0.0219       -0.0656      0.0365  \n 2005  -0.0764     0.0315       -0.1497     -0.0031 *\n 2006  -0.0462     0.0221       -0.0977      0.0053  \n 2007  -0.0396     0.0128       -0.0695     -0.0097 *\n---\nSignif. codes: `*' confidence band does not cover 0\n\nControl Group:  Never Treated,  Anticipation Periods:  0\nEstimation Method:  Doubly Robust\n```\n\n\n:::\n\n```{.r .cell-code}\nggdid(calendar_att,\n      title  = \"Calendar-Time ATTs: Programme Impact by Year\",\n      xlab   = \"Calendar Year\",\n      ylab   = expression(theta^{cal}(t)),\n      legend = FALSE) +\n  theme_minimal(base_size = 13)\n```\n\n::: {.cell-output-display}\n![Calendar-time ATTs map the programme's aggregate impact to specific fiscal periods, directly useful for financial reporting and board-level summaries.](did_for_ceos_files/figure-html/calendar-effects-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n### Step 7: TWFE vs CS: A Direct Comparison\n\nA natural question is: how different is the CS estimate from the TWFE coefficient analysts have been reporting for decades? The code below runs both estimators on the same data and plots the results side by side.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nmpdta_twfe <- mpdta |>\n  mutate(treated_post = as.integer(year >= first.treat & first.treat > 0))\n\n# Note: treated_post collapses all post-treatment periods into a single indicator,\n# which does not distinguish dynamic treatment effects. This is a simplified\n# TWFE specification designed for benchmarking purposes and is not directly\n# comparable to the cohort-time ATT(g,t) estimates from CS.\ntwfe_fit <- feols(lemp ~ treated_post | countyreal + year,\n                  data    = mpdta_twfe,\n                  cluster = ~countyreal)\n\ntwfe_coef <- coef(twfe_fit)[\"treated_post\"]\ntwfe_se   <- se(twfe_fit)[\"treated_post\"]\ncs_coef   <- group_att$overall.att\ncs_se     <- group_att$overall.se\n\ncomparison_df <- tibble(\n  Method   = c(\"TWFE\\n(standard)\", \"Callaway &\\nSant'Anna\"),\n  Estimate = c(twfe_coef, cs_coef),\n  SE       = c(twfe_se, cs_se),\n  Lower    = c(twfe_coef - 1.96 * twfe_se, cs_coef - 1.96 * cs_se),\n  Upper    = c(twfe_coef + 1.96 * twfe_se, cs_coef + 1.96 * cs_se)\n)\n\nggplot(comparison_df, aes(x = Method, y = Estimate, colour = Method)) +\n  geom_hline(yintercept = 0, linetype = \"dashed\", colour = \"grey50\") +\n  geom_point(size = 5) +\n  geom_errorbar(aes(ymin = Lower, ymax = Upper), width = 0.15, linewidth = 1.2) +\n  scale_colour_manual(values = c(\n    \"TWFE\\n(standard)\"      = \"#E74C3C\",\n    \"Callaway &\\nSant'Anna\" = \"#27AE60\"\n  )) +\n  labs(\n    title    = \"TWFE vs Callaway–Sant'Anna: Overall ATT Comparison\",\n    subtitle = \"CS uses the cohort-specific aggregator (recommended); TWFE uses the standard two-way FE regression\",\n    y        = \"Estimated ATT (log employment)\",\n    x        = NULL,\n    caption  = \"Error bars show 95% confidence intervals. Data: mpdta.\"\n  ) +\n  theme_minimal(base_size = 13) +\n  theme(legend.position     = \"none\",\n        panel.grid.minor    = element_blank(),\n        panel.grid.major.x  = element_blank())\n```\n\n::: {.cell-output-display}\n![TWFE produces a single coefficient that conflates effects across cohorts, calendar times, and exposure lengths. In this dataset both estimates are negative (minimum wages reduce teen employment), but the magnitude and precision differ, and the TWFE estimate carries no clean heterogeneity breakdown.](did_for_ceos_files/figure-html/twfe-comparison-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n---\n\n## Part VI: A Diagnostic Checklist for Practitioners {#part-vi}\n\nBefore presenting any DiD analysis to leadership, verify the following across three dimensions: research design, estimation, and reporting.\n\n### Design Checklist\n\n- [ ] **Control cohort defined and justified**: Is the comparison group plausibly on the same outcome trend as the treated cohort in the absence of treatment?\n- [ ] **Parallel trends assessed**: Both via institutional knowledge *and* empirical pre-trends test.\n- [ ] **No anticipation evaluated**: Did units change behaviour before treatment formally began?\n- [ ] **SUTVA considered**: Could treated units contaminate the control group via spillovers or general equilibrium effects?\n\n### Estimation Checklist\n\n- [ ] **CS estimator used** (not TWFE) when staggered adoption and heterogeneous effects are plausible. TWFE remains acceptable when treatment effects are homogeneous or all units are treated simultaneously.\n- [ ] **Covariates included** if cohorts differ in pre-treatment characteristics that drive outcome trends.\n- [ ] **Doubly robust estimator selected** (`est_method = \"dr\"`) unless there is a specific reason to prefer OR or IPW alone.\n- [ ] **Comparison group choice documented**: `nevertreated` vs `notyettreated`, and the rationale for the choice.\n- [ ] **Multiplier bootstrap used** for simultaneous confidence bands across event times.\n\n### Reporting Checklist\n\n- [ ] **ATT(g,t) heatmap** presented, or at minimum by-cohort event studies.\n- [ ] **Pre-trends diagnostic** explicitly reported with coefficient estimates and joint test p-values.\n- [ ] **Aggregation method stated and justified**: which business question is being answered?\n- [ ] **TWFE comparison provided** as a robustness and benchmarking check.\n- [ ] **Sensitivity analysis discussed**: how robust are conclusions to modest violations of parallel trends?\n\n### When to Stop\n\nSome conditions should trigger reassessment before proceeding:\n\n| Red Flag | Implication |\n|:---------|:-----------|\n| Pre-treatment ATTs are large and statistically significant | Parallel trends likely violated; results not credible |\n| Nearly all units eventually treated and comparison group is tiny | Low power; consider Synthetic Control instead |\n| Massive spillovers from treated to control units | ATT underestimated; redesign the comparison group |\n| Treatment turns on and off across periods | Standard CS framework not applicable; consider de Chaisemartin & D'Haultfoeuille (2020) |\n\n: Conditions that should trigger reassessment before proceeding {.striped}\n\n---\n\n## Part VII: Five Questions for Your Analytics Team {#part-vii}\n\nIf your organisation is using DiD to evaluate strategic initiatives, these five questions will quickly reveal whether the analysis is methodologically sound.\n\n**1. \"Did you use TWFE or a modern staggered DiD estimator?\"**\nIf the team ran a TWFE regression on a staggered rollout, the estimate may be biased when treatment effects vary across cohorts or over time. Ask for the Goodman-Bacon decomposition to see how much weight comes from contaminated comparisons (late-treated units against already-treated units).\n\n**2. \"Can you show me the ATT(g,t) matrix?\"**\nIf they can only show a single coefficient, all heterogeneity information is hidden. Modern DiD should show effects by cohort and by exposure duration. A single number is a starting point, not a conclusion.\n\n**3. \"What does the pre-trend test show?\"**\nNot just \"it looks parallel\": what are the actual coefficient estimates for pre-treatment periods? What is the p-value for the joint test that all pre-treatment coefficients are zero? Are simultaneous bands (not pointwise) being used?\n\n**4. \"What does the event study tell us about dynamics?\"**\nA positive effect at $e=0$ that grows to a larger effect at $e=4$ is a very different strategic story than a large effect at $e=0$ that decays to zero by $e=4$. The first suggests a programme that takes time to mature; the second, one that is effective only for early adopters or fades with habituation. TWFE cannot distinguish these narratives. The CS event study can.\n\n**5. \"How sensitive are the conclusions to violations of parallel trends?\"**\nUnder the HonestDiD framework (Rambachan & Roth, 2023), you can bound conclusions under specified violations. If the \"the programme worked\" finding holds even when parallel trends is violated by 50% of its magnitude, you have a robust result. If it collapses under a 5% violation, caution is warranted regardless of the pre-test outcome.\n\n---\n\n## Conclusion: From Statistical Methodology to Competitive Advantage\n\nThe organisations that will win in the next decade are not those with the most data. They are those with the best **causal models**: the ability to know with confidence what actually drives results, and therefore where to invest next.\n\nModern DiD, particularly the Callaway and Sant'Anna estimator, is not a technical refinement for academic purists. It is a practical tool that:\n\n- Produces estimates with unambiguous economic interpretations: $ATT(g,t)$ means what it says\n- Uses more transparent, researcher-controlled weighting schemes (cohort size, not statistical variance), though some aggregators such as calendar-time still involve implicit weights that should be interpreted carefully\n- Provides honest pre-testing that does not rely on contaminated comparisons\n- Delivers doubly robust inference that protects against common modelling errors\n- Enables heterogeneity analysis that can reshape targeting and rollout strategy\n\nThat said, TWFE remains valid when treatment effects are homogeneous across cohorts and time, or when all units are treated simultaneously. The CS framework is not a blanket replacement; it is the right tool when the standard assumptions behind TWFE are implausible, which in staggered settings they usually are.\n\nTwo closely related alternatives are worth noting for practitioners: Sun & Abraham (2021) propose an interaction-weighted estimator that is asymptotically equivalent to CS but estimated within a single regression framework, which some practitioners find more familiar; and de Chaisemartin & D'Haultfœuille (2020) extend the analysis to settings where treatment can be turned on and off across periods.\n\nThe `did` package makes this accessible to any analyst who can run a regression. The question is not whether you can afford to use modern methods. It is whether you can afford not to.\n\n---\n\n## References {#references .unnumbered}\n\nBaker, A., Callaway, B., Cunningham, S., Goodman-Bacon, A., & Sant'Anna, P. H. C. (2026). Difference-in-differences designs: A practitioner's guide. *Journal of Economic Literature*, 64(2), 498–557.\n\nCallaway, B., & Sant'Anna, P. H. C. (2021). Difference-in-Differences with multiple time periods. *Journal of Econometrics*, 225(2), 200–230. <https://doi.org/10.1016/j.jeconom.2020.12.001>\n\nde Chaisemartin, C., & D'Haultfœuille, X. (2020). Two-way fixed effects estimators with heterogeneous treatment effects. *American Economic Review*, 110(9), 2964–2996.\n\nGoodman-Bacon, A. (2021). Difference-in-Differences with variation in treatment timing. *Journal of Econometrics*, 225(2), 254–277.\n\nHolland, P. W. (1986). Statistics and causal inference. *Journal of the American Statistical Association*, 81(396), 945–960.\n\nRambachan, A., & Roth, J. (2023). A more credible approach to parallel trends. *Review of Economic Studies*, 90(5), 2555–2591.\n\nRoth, J. (2022). Pre-test with caution: Event-study estimates after testing for parallel trends. *American Economic Review: Insights*, 4(3), 305–322.\n\nRoth, J., Sant'Anna, P. H. C., Bilinski, A., & Poe, J. (2023). What's trending in difference-in-differences? A synthesis of the recent econometrics literature. *Journal of Econometrics*, 235(2), 2218–2244.\n\nSant'Anna, P. H. C., & Zhao, J. (2020). Doubly robust difference-in-differences estimators. *Journal of Econometrics*, 219(1), 101–122.\n\nSun, L., & Abraham, S. (2021). Estimating dynamic treatment effects in event studies with heterogeneous treatment effects. *Journal of Econometrics*, 225(2), 175–199.\n",
    "supporting": [
      "did_for_ceos_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}