<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-09-21">
<meta name="description" content="A sixteen-year projection disaggregated by NUTS III region and schooling cycle. Cumulative recruitment reaches 90,575 teachers, an average of 5,661 a year, against a historical mean of 4,537. Between 58 and 64 per cent of the 2024 workforce retires within the horizon, and the system recruits fewer teachers than it loses because the number of posts is falling.">

<title>Projecting teacher requirements in mainland Portugal to 2040 – The Causal Layer</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../foto3.jpeg" rel="icon" type="image/jpeg">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-6b6957c917596b414ec0b78690761e87.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-de63f62b328812d8e578a4d74e282472.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-c3ec530b6f8a19b58ffd72ce98371a5e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark-6ea507b90afd36dfcf636ae1abab9ce3.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="../../site_libs/bootstrap/bootstrap-c3ec530b6f8a19b58ffd72ce98371a5e.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../foto3.jpeg" alt="" class="navbar-logo light-content">
    <img src="../../foto3.jpeg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">The Causal Layer</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-series" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Series</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-series">    
        <li>
    <a class="dropdown-item" href="../../series.html">
 <span class="dropdown-text">All Series</span></a>
  </li>  
        <li><hr class="dropdown-divider"></li>
        <li>
    <a class="dropdown-item" href="../../series/causal-inference.html">
 <span class="dropdown-text">Causal Inference</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../series/pricing.html">
 <span class="dropdown-text">Pricing &amp; Demand</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../series/forecasting.html">
 <span class="dropdown-text">Forecasting</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../posts.html"> 
<span class="menu-text">All Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../resources.html"> 
<span class="menu-text">Resources</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/joao-vieira-iseg/"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:joaoviei7a@gmail.com"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="../../index.xml"> <i class="bi bi-rss" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-problem" id="toc-the-problem" class="nav-link active" data-scroll-target="#the-problem">The problem</a></li>
  <li><a href="#what-this-projection-does-in-one-chapter" id="toc-what-this-projection-does-in-one-chapter" class="nav-link" data-scroll-target="#what-this-projection-does-in-one-chapter">What this projection does, in one chapter</a></li>
  <li><a href="#what-it-found" id="toc-what-it-found" class="nav-link" data-scroll-target="#what-it-found">What it found</a></li>
  <li><a href="#the-channel-that-binds" id="toc-the-channel-that-binds" class="nav-link" data-scroll-target="#the-channel-that-binds">The channel that binds</a></li>
  <li><a href="#what-the-result-rests-on" id="toc-what-the-result-rests-on" class="nav-link" data-scroll-target="#what-the-result-rests-on">What the result rests on</a></li>
  <li><a href="#what-transfers" id="toc-what-transfers" class="nav-link" data-scroll-target="#what-transfers">What transfers</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Projecting teacher requirements in mainland Portugal to 2040</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
  <div class="quarto-categories">
    <div class="quarto-category">forecasting</div>
    <div class="quarto-category">workforce</div>
    <div class="quarto-category">public policy</div>
  </div>
  </div>

<div>
  <div class="description">
    A sixteen-year projection disaggregated by NUTS III region and schooling cycle. Cumulative recruitment reaches 90,575 teachers, an average of 5,661 a year, against a historical mean of 4,537. Between 58 and 64 per cent of the 2024 workforce retires within the horizon, and the system recruits fewer teachers than it loses because the number of posts is falling.
  </div>
</div>


<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 21, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-problem" class="level2">
<h2 class="anchored" data-anchor-id="the-problem">The problem</h2>
<p>Two demographic transitions are running through the Portuguese school system at the same time, and they move in opposite directions. Births fell, and the smaller cohorts work their way up through the cycles of schooling with a predictable lag, so enrolment declines first in pre-school and the first cycle and then at the levels above. Meanwhile the teaching workforce sits heavily in the upper age bands, the legacy of a long stretch of low recruitment that interrupted generational renewal.</p>
<p>The first transition reduces the number of teaching posts the system requires. The second obliges it to replace a growing share of the people who occupy them. Which of the two dominates is an empirical question, and the answer is not the intuitive one.</p>
<p>The reference study makes the arithmetic explicit. Total enrolment in mainland public schools falls to 1,078,353 pupils in 2034/35, about five per cent below 2025/26, while the teachers active in 2024/25 who remain in service fall from 121,884 to 76,293, a reduction of thirty-seven per cent (Nunes et al., 2025). Recruitment need is the difference between two falling quantities, and it is governed by the faster one. A contraction of five per cent on the demand side cannot absorb a contraction of thirty-seven per cent on the supply side.</p>
<p>That is why the official projection puts cumulative recruitment at 38,779 new teachers to 2034/35, an average close to 3,800 a year in a system that is shrinking. The figure is worth holding onto, because everything below eventually comes back to it.</p>
</section>
<section id="what-this-projection-does-in-one-chapter" class="level2">
<h2 class="anchored" data-anchor-id="what-this-projection-does-in-one-chapter">What this projection does, in one chapter</h2>
<p>We built an independent projection of teacher requirements for mainland Portugal, by NUTS III region and schooling cycle, running from 2025 to 2040. It is assembled from published statistics, and the code that produced every figure is released with it, which places it on different footing from the official studies, whose reliance on individual-level administrative records puts them beyond replication.</p>
<p>The chain has six linked blocks, each writing a file the next one reads:</p>
<ul>
<li>enrolment, projected from the school-age population and a coverage rate;</li>
<li>demand, converting pupils into posts;</li>
<li>supply, ageing the existing workforce forward and computing the recruitment needed to close the distance to demand;</li>
<li>the training constraint, asking whether the qualifying pipeline can deliver those recruits;</li>
<li>uncertainty, propagated by simulation over stated assumptions;</li>
<li>validation, which reads every other block and feeds none of them.</li>
</ul>
<p>Demand rests on a student-teacher ratio, and the behaviour of that ratio over sixteen years is the single assumption that most affects the result. Rather than fixing it by convention, we compared ten candidate projection methods in a rolling-origin bake-off and let the backtest select per cell. Separately, the enrolment elasticity of teacher demand was tested against the conventional assumption of strict proportionality. The estimate of 0.506 survived that test in one cell only, and it is deployed in that cell alone; everywhere else the chain reverts to proportionality.</p>
<p>Supply is a cohort chain over nine age bands with age-specific exit hazards, and entry is set endogenously as whatever recruitment would restore the stock implied by projected demand. Nothing in the supply block limits how many people are available to be recruited.</p>
<p>That is the design choice that separates this exercise from the official studies. Requirement and feasibility are answered by different blocks. The supply block says how many teachers must be hired. The training constraint block asks whether they exist. Those questions have different answers, and the graduate constraint is applied only to the channel that initial teacher education actually governs, rather than to the total.</p>
<p>One more distinction carries every headline number. The supply block publishes two recruitment paths. The flat chain applies a uniform statutory exit age; the tenure queue models exit through accumulated service. The figures below are the flat chain unless stated otherwise. Derivations of the method, the bake-off tables, the elasticity estimation and the wild cluster bootstrap that supports it, the hindcast, and the data-preparation defects all sit in the <a href="../../projects/teacher-forecasting/teacher_requirements_mainland_portugal_2025_2040.html">full report</a>.</p>
</section>
<section id="what-it-found" class="level2">
<h2 class="anchored" data-anchor-id="what-it-found">What it found</h2>
<p>Over 2025 to 2040 the live flat chain requires 90,575 recruitments, an average of 5,661 a year. The tenure queue puts the same quantity at 98,579. The first decade alone accounts for 55,045, an average of 5,505 a year on the smoothed path.</p>
<p>Total exits over the horizon come to 96,908 against a requirement of 90,575, so replacement is 107.0 per cent of recruitment and the expansion component is negative in all sixteen years. Of those exits, 81,260 are retirements and 15,648 are attrition below age 55, roughly a sixth of the total. Between 58.4 and 63.6 per cent of the 2024 workforce retires inside the horizon, depending on the specification.</p>
<div id="fig-wave" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-wave-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/wave_vs_recruitment.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-wave-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Retirement wave against the projected recruitment path, 2025-2040.
</figcaption>
</figure>
</div>
<p><a href="#fig-wave" class="quarto-xref">Figure&nbsp;1</a> shows why the requirement does not ease. The wave does not pass within the window. The stock aged 55 and over falls only 8.5 per cent over sixteen years, and the band aged 60 and above is larger in 2040 than it was in 2024. The system replaces an ageing corps with recruits who then age into the same bands.</p>
<div id="fig-pyramid" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pyramid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/age_pyramid_today_vs_2040.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pyramid-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Age structure of the teaching workforce, 2024 against 2040.
</figcaption>
</figure>
</div>
<p><a href="#fig-pyramid" class="quarto-xref">Figure&nbsp;2</a> makes the same point structurally. The distribution shifts, but it does not rejuvenate.</p>
<p>Set against the system’s own history, the ask is demanding without being unprecedented. No projected year exceeds the all-time high of 6,298 entries recorded in 2020. Eight of the sixteen projected years exceed the second-highest year on record. A requirement that sits above the second-best year for half the horizon is a serious test of a recruitment apparatus, measured against what that apparatus has actually delivered.</p>
<div id="fig-regional" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-regional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/cumulative_recruitment_nuts3.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-regional-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Cumulative recruitment requirement by NUTS III region.
</figcaption>
</figure>
</div>
<p>Territorially, the requirement concentrates. Three regions carry 43.70 per cent of the national total, as <a href="#fig-regional" class="quarto-xref">Figure&nbsp;3</a> shows. Two cautions attach to reading that map. Regional requirement is where the posts are, not where the teachers come from: forty-two per cent of teachers holding a master’s degree obtained after 2013 teach in a region different from the one in which they qualified (Nunes et al., 2025). And accuracy in projections of labour demand falls as the horizon lengthens and as the geography disaggregates (Richardson and Tan, 2007), which applies with full force here.</p>
<p>Against the official benchmark of 38,779 to 2034/35, our first-decade figure is 41.9 per cent higher raw, and 24.5 per cent higher after a perimeter adjustment of 1.140 that reconciles the two workforce universes. The residual is not explained by anything we can identify in the available data, and we do not present either estimate as the correct one.</p>
<div id="tbl-headline" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-headline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Headline quantities, mainland Portugal, 2025-2040
</figcaption>
<div aria-describedby="tbl-headline-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Quantity</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Recruitment requirement, 2025-2040 (flat chain)</td>
<td style="text-align: right;">90,575</td>
</tr>
<tr class="even">
<td>Recruitment requirement (tenure queue)</td>
<td style="text-align: right;">98,579</td>
</tr>
<tr class="odd">
<td>Total exits</td>
<td style="text-align: right;">96,908</td>
</tr>
<tr class="even">
<td>Retirements</td>
<td style="text-align: right;">81,260</td>
</tr>
<tr class="odd">
<td>Attrition below 55</td>
<td style="text-align: right;">15,648</td>
</tr>
<tr class="even">
<td>Graduate channel requirement (27.68%)</td>
<td style="text-align: right;">25,072</td>
</tr>
<tr class="odd">
<td>Lateral channel requirement (72.32%)</td>
<td style="text-align: right;">65,503</td>
</tr>
<tr class="even">
<td>Feasible graduate entries</td>
<td style="text-align: right;">40,208</td>
</tr>
<tr class="odd">
<td>Feasible lateral entries</td>
<td style="text-align: right;">58,764</td>
</tr>
<tr class="even">
<td>Cumulative graduate surplus</td>
<td style="text-align: right;">15,136</td>
</tr>
<tr class="odd">
<td>Cumulative lateral shortfall</td>
<td style="text-align: right;">6,765</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="the-channel-that-binds" class="level2">
<h2 class="anchored" data-anchor-id="the-channel-that-binds">The channel that binds</h2>
<p>Entry into teaching happens through two routes, and the chain keeps them apart. The split is 27.68 per cent graduate and 72.32 per cent lateral, estimated from the entry age profile of recent years. In levels, that is 25,072 recruits the graduate channel must deliver and 65,503 the lateral channel must deliver.</p>
<div id="fig-channels" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-channels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/channel_split.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-channels-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Coverage by entry channel, graduate against lateral, 2025-2040.
</figcaption>
</figure>
</div>
<p><a href="#fig-channels" class="quarto-xref">Figure&nbsp;4</a> reports coverage, defined as feasible entries over required entries. The graduate channel never falls below 148.5 per cent. It starts at 189.1 per cent and ends at 154.1 per cent, and the constraint never binds in any of the sixteen years. Initial teacher education, on these numbers, is not the binding constraint on the recruitment path.</p>
<p>The lateral channel is. Coverage drops below 100 per cent from 2026 and reaches 83.3 per cent by 2036, leaving 6,765 positions unfilled over the horizon. Cumulatively the graduate channel runs a surplus of 15,136.</p>
<p>The reported shortfall of 6,765 exists only because we refuse to offset one channel against the other. Netting the channels reports exactly zero unmet need in every year, and the two ways of combining them differ by 15,304 teachers. Readers who prefer the netted convention should see plainly that it removes the entire deficit. Our reason for refusing is that the two channels draw on different populations: a surplus of new graduates does not staff a post that requires an experienced re-entrant, and the age profile underlying the split does not support the substitution.</p>
<p>Against that, a limitation of the same magnitude. The lateral channel is projected as a fixed rate applied to a falling workforce. There is no stock model of the contracted reserve anywhere in the chain, because the Portuguese data do not measure it. The channel that binds is the one we model least well.</p>
</section>
<section id="what-the-result-rests-on" class="level2">
<h2 class="anchored" data-anchor-id="what-the-result-rests-on">What the result rests on</h2>
<p>Three dependencies govern the sign and the level of what is reported above. None of them is an estimate in the ordinary sense.</p>
<p>The first is an external anchor. The conversion rate from qualified graduate to placed teacher is scaled by a factor of 1.6243, an uplift of 62.4 per cent on observed graduate entries, to reconcile the estimated flow with an external estimate of the graduate entry level. Anchored, the mean graduate gap is a surplus of 946 a year. Unanchored, it is a shortage of 19.9. The sign reverses. The validation suite records this as a failure rather than as a caveat, and the anchor is documented in full at <a href="../../projects/teacher-forecasting/teacher_requirements_mainland_portugal_2025_2040.html">full report</a>.</p>
<p>The second is the descriptive student-teacher ratio. It records the staffing that occurred, including posts that went unfilled, so if the system was short of teachers during the observation window the ratio is biased upward and projected demand is biased downward. The mechanism is old and well documented: a system short of teachers adjusts by relaxing qualification requirements and raising the workload of the teachers it has, and those adjustments are absorbed into the observed ratio (Santiago, 2002). We impose no normative target anywhere in the chain. The requirement reported here is a lower bound.</p>
<p>The third is the retirement hazard for the band aged 60 and above. It is set from the statutory exit age rather than estimated from the data, and the three estimated alternatives are all lower. That single assumption generates 94.7 per cent of the retirement wave, which in turn generates the recruitment requirement. Describing it as an estimate would be wrong.</p>
<p>Beyond the three, one quantity sits entirely outside every figure in this post. The substitution reserve, the pool of contracted teachers who cover absences and temporary vacancies during the school year, is not modelled at any point. At twenty per cent of the 2025 stock it would amount to 27,722 teachers, which is 4.10 times the shortfall the chain reports. The age-band sum of 139,098 on which the supply block works, and the reference census of approximately 122,000 active teachers in mainland public education, describe different universes, and comparisons that cross them are not like for like.</p>
</section>
<section id="what-transfers" class="level2">
<h2 class="anchored" data-anchor-id="what-transfers">What transfers</h2>
<p>Three things about this exercise generalise to projections of the same family.</p>
<div id="fig-variance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/variance_decomposition.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-variance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Variance decomposition of the projected deficits.
</figcaption>
</figure>
</div>
<p>The variance decomposition inverts between the two deficits, as <a href="#fig-variance" class="quarto-xref">Figure&nbsp;5</a> shows. On the graduate gap, the conversion rate accounts for 84.3 per cent of the variance; on the combined gap, the same parameter accounts for 3.5 per cent, while the lateral reserve accounts for 70.3 per cent. Reporting one decomposition therefore selects the answer by selecting the target. Any sensitivity analysis that names a single dominant driver should be read alongside the question of what deficit it was computed on.</p>
<p>The validation suite reports sixteen passes among twenty evidential checks, not twenty-three among twenty-seven. Seven of the twenty-seven hold by construction: the quantities they compare are built from the same inputs and agree because the arithmetic requires it. A definition is not a finding, and counting it as one inflates the apparent standing of the result. The full count and the reasoning behind each exclusion are at <code>PROJECT_URL</code>.</p>
<p>And a single organisational assumption moves the reference study’s own requirement from 38,779 to between 15,579 and 16,474 (Nunes et al., 2025). Those alternative scenarios reallocate teachers’ classroom availability fully to classroom needs. The range they open is larger than the entire gap between the two studies, which places roughly six in every ten projected recruitments in the domain of how schools are organised rather than in the domain of demography. The replacement and expansion decomposition used above is a standard international framing for exactly this reason (Bruneforth, Gagnon and Wallet, 2009): it separates what the population does from what the institution does.</p>
<p>You should use these figures as a lower bound on permanent posts under stated assumptions, not as a forecast of hires. The requirement is bounded below because the ratio is descriptive; the feasibility verdict flips sign if you remove the anchor; the deficit is zero if you net the channels; and the substitution reserve is absent throughout. If you disagree with the anchor, the ratio, or the channel split, the code is released so that the disagreement can be made precise.</p>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<p>Bruneforth, M., Gagnon, A. and Wallet, P. (2009). <em>Projecting the global demand for teachers: Meeting the goal of universal primary education by 2015</em>. Technical Paper No.&nbsp;3. Montreal: UNESCO Institute for Statistics.</p>
<p>Nunes, L. C., Gomes, S., Capelo, C., Gião, J., Duarte, J., Ferreira, A. P. and Silva, P. L. (2025). <em>Estudo de diagnóstico de necessidades docentes de 2025 a 2034</em>. Lisbon: Direção-Geral de Estatísticas da Educação e Ciência.</p>
<p>Richardson, S. and Tan, Y. (2007). <em>Forecasting future demands: What we can and cannot know</em>. Adelaide: National Centre for Vocational Education Research.</p>
<p>Santiago, P. (2002). <em>Teacher demand and supply: Improving teaching quality and addressing teacher shortages</em>. OECD Education Working Papers, No.&nbsp;1. Paris: OECD Publishing. [VERIFY]</p>


<!-- -->

</section>

<a onclick="window.scrollTo(0, 0); return false;" role="button" id="quarto-back-to-top"><i class="bi bi-arrow-up"></i> Back to top</a></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/joaovieira22\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // target, if specified
            link.setAttribute("target", "_blank");
            if (link.getAttribute("rel") === null) {
              link.setAttribute("rel", "noopener");
            }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Projecting teacher requirements in mainland Portugal to 2040"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">description:</span><span class="co"> "A sixteen-year projection disaggregated by NUTS III region and schooling cycle. Cumulative recruitment reaches 90,575 teachers, an average of 5,661 a year, against a historical mean of 4,537. Between 58 and 64 per cent of the 2024 workforce retires within the horizon, and the system recruits fewer teachers than it loses because the number of posts is falling."</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="an">date:</span><span class="co"> 2026-09-21</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="an">categories:</span><span class="co"> [forecasting, workforce, public policy]</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="fu">## The problem</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>Two demographic transitions are running through the Portuguese school system at the same time, and they move in opposite directions. Births fell, and the smaller cohorts work their way up through the cycles of schooling with a predictable lag, so enrolment declines first in pre-school and the first cycle and then at the levels above. Meanwhile the teaching workforce sits heavily in the upper age bands, the legacy of a long stretch of low recruitment that interrupted generational renewal.</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>The first transition reduces the number of teaching posts the system requires. The second obliges it to replace a growing share of the people who occupy them. Which of the two dominates is an empirical question, and the answer is not the intuitive one.</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>The reference study makes the arithmetic explicit. Total enrolment in mainland public schools falls to 1,078,353 pupils in 2034/35, about five per cent below 2025/26, while the teachers active in 2024/25 who remain in service fall from 121,884 to 76,293, a reduction of thirty-seven per cent (Nunes et al., 2025). Recruitment need is the difference between two falling quantities, and it is governed by the faster one. A contraction of five per cent on the demand side cannot absorb a contraction of thirty-seven per cent on the supply side.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>That is why the official projection puts cumulative recruitment at 38,779 new teachers to 2034/35, an average close to 3,800 a year in a system that is shrinking. The figure is worth holding onto, because everything below eventually comes back to it.</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="fu">## What this projection does, in one chapter</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>We built an independent projection of teacher requirements for mainland Portugal, by NUTS III region and schooling cycle, running from 2025 to 2040. It is assembled from published statistics, and the code that produced every figure is released with it, which places it on different footing from the official studies, whose reliance on individual-level administrative records puts them beyond replication.</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>The chain has six linked blocks, each writing a file the next one reads:</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>enrolment, projected from the school-age population and a coverage rate;</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>demand, converting pupils into posts;</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>supply, ageing the existing workforce forward and computing the recruitment needed to close the distance to demand;</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>the training constraint, asking whether the qualifying pipeline can deliver those recruits;</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>uncertainty, propagated by simulation over stated assumptions;</span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>validation, which reads every other block and feeds none of them.</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>Demand rests on a student-teacher ratio, and the behaviour of that ratio over sixteen years is the single assumption that most affects the result. Rather than fixing it by convention, we compared ten candidate projection methods in a rolling-origin bake-off and let the backtest select per cell. Separately, the enrolment elasticity of teacher demand was tested against the conventional assumption of strict proportionality. The estimate of 0.506 survived that test in one cell only, and it is deployed in that cell alone; everywhere else the chain reverts to proportionality.</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>Supply is a cohort chain over nine age bands with age-specific exit hazards, and entry is set endogenously as whatever recruitment would restore the stock implied by projected demand. Nothing in the supply block limits how many people are available to be recruited.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a>That is the design choice that separates this exercise from the official studies. Requirement and feasibility are answered by different blocks. The supply block says how many teachers must be hired. The training constraint block asks whether they exist. Those questions have different answers, and the graduate constraint is applied only to the channel that initial teacher education actually governs, rather than to the total.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>One more distinction carries every headline number. The supply block publishes two recruitment paths. The flat chain applies a uniform statutory exit age; the tenure queue models exit through accumulated service. The figures below are the flat chain unless stated otherwise. Derivations of the method, the bake-off tables, the elasticity estimation and the wild cluster bootstrap that supports it, the hindcast, and the data-preparation defects all sit in the <span class="co">[</span><span class="ot">full report</span><span class="co">](/projects/teacher-forecasting/teacher_requirements_mainland_portugal_2025_2040.qmd)</span>.</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a><span class="fu">## What it found</span></span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>Over 2025 to 2040 the live flat chain requires 90,575 recruitments, an average of 5,661 a year. The tenure queue puts the same quantity at 98,579. The first decade alone accounts for 55,045, an average of 5,505 a year on the smoothed path.</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>Total exits over the horizon come to 96,908 against a requirement of 90,575, so replacement is 107.0 per cent of recruitment and the expansion component is negative in all sixteen years. Of those exits, 81,260 are retirements and 15,648 are attrition below age 55, roughly a sixth of the total. Between 58.4 and 63.6 per cent of the 2024 workforce retires inside the horizon, depending on the specification.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="al">![Retirement wave against the projected recruitment path, 2025-2040.](figures/wave_vs_recruitment.png)</span>{#fig-wave width=100%}</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>@fig-wave shows why the requirement does not ease. The wave does not pass within the window. The stock aged 55 and over falls only 8.5 per cent over sixteen years, and the band aged 60 and above is larger in 2040 than it was in 2024. The system replaces an ageing corps with recruits who then age into the same bands.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="al">![Age structure of the teaching workforce, 2024 against 2040.](figures/age_pyramid_today_vs_2040.png)</span>{#fig-pyramid width=100%}</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>@fig-pyramid makes the same point structurally. The distribution shifts, but it does not rejuvenate.</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>Set against the system's own history, the ask is demanding without being unprecedented. No projected year exceeds the all-time high of 6,298 entries recorded in 2020. Eight of the sixteen projected years exceed the second-highest year on record. A requirement that sits above the second-best year for half the horizon is a serious test of a recruitment apparatus, measured against what that apparatus has actually delivered.</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a><span class="al">![Cumulative recruitment requirement by NUTS III region.](figures/cumulative_recruitment_nuts3.png)</span>{#fig-regional width=100%}</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>Territorially, the requirement concentrates. Three regions carry 43.70 per cent of the national total, as @fig-regional shows. Two cautions attach to reading that map. Regional requirement is where the posts are, not where the teachers come from: forty-two per cent of teachers holding a master's degree obtained after 2013 teach in a region different from the one in which they qualified (Nunes et al., 2025). And accuracy in projections of labour demand falls as the horizon lengthens and as the geography disaggregates (Richardson and Tan, 2007), which applies with full force here.</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>Against the official benchmark of 38,779 to 2034/35, our first-decade figure is 41.9 per cent higher raw, and 24.5 per cent higher after a perimeter adjustment of 1.140 that reconciles the two workforce universes. The residual is not explained by anything we can identify in the available data, and we do not present either estimate as the correct one.</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Quantity <span class="pp">|</span> Value <span class="pp">|</span></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a><span class="pp">|---|---:|</span></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Recruitment requirement, 2025-2040 (flat chain) <span class="pp">|</span> 90,575 <span class="pp">|</span></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Recruitment requirement (tenure queue) <span class="pp">|</span> 98,579 <span class="pp">|</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Total exits <span class="pp">|</span> 96,908 <span class="pp">|</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Retirements <span class="pp">|</span> 81,260 <span class="pp">|</span></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Attrition below 55 <span class="pp">|</span> 15,648 <span class="pp">|</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Graduate channel requirement (27.68%) <span class="pp">|</span> 25,072 <span class="pp">|</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Lateral channel requirement (72.32%) <span class="pp">|</span> 65,503 <span class="pp">|</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Feasible graduate entries <span class="pp">|</span> 40,208 <span class="pp">|</span></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Feasible lateral entries <span class="pp">|</span> 58,764 <span class="pp">|</span></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cumulative graduate surplus <span class="pp">|</span> 15,136 <span class="pp">|</span></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="pp">|</span> Cumulative lateral shortfall <span class="pp">|</span> 6,765 <span class="pp">|</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a>: Headline quantities, mainland Portugal, 2025-2040 {#tbl-headline}</span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="fu">## The channel that binds</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Entry into teaching happens through two routes, and the chain keeps them apart. The split is 27.68 per cent graduate and 72.32 per cent lateral, estimated from the entry age profile of recent years. In levels, that is 25,072 recruits the graduate channel must deliver and 65,503 the lateral channel must deliver.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="al">![Coverage by entry channel, graduate against lateral, 2025-2040.](figures/channel_split.png)</span>{#fig-channels width=100%}</span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>@fig-channels reports coverage, defined as feasible entries over required entries. The graduate channel never falls below 148.5 per cent. It starts at 189.1 per cent and ends at 154.1 per cent, and the constraint never binds in any of the sixteen years. Initial teacher education, on these numbers, is not the binding constraint on the recruitment path.</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>The lateral channel is. Coverage drops below 100 per cent from 2026 and reaches 83.3 per cent by 2036, leaving 6,765 positions unfilled over the horizon. Cumulatively the graduate channel runs a surplus of 15,136.</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>The reported shortfall of 6,765 exists only because we refuse to offset one channel against the other. Netting the channels reports exactly zero unmet need in every year, and the two ways of combining them differ by 15,304 teachers. Readers who prefer the netted convention should see plainly that it removes the entire deficit. Our reason for refusing is that the two channels draw on different populations: a surplus of new graduates does not staff a post that requires an experienced re-entrant, and the age profile underlying the split does not support the substitution.</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>Against that, a limitation of the same magnitude. The lateral channel is projected as a fixed rate applied to a falling workforce. There is no stock model of the contracted reserve anywhere in the chain, because the Portuguese data do not measure it. The channel that binds is the one we model least well.</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a><span class="fu">## What the result rests on</span></span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a>Three dependencies govern the sign and the level of what is reported above. None of them is an estimate in the ordinary sense.</span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a>The first is an external anchor. The conversion rate from qualified graduate to placed teacher is scaled by a factor of 1.6243, an uplift of 62.4 per cent on observed graduate entries, to reconcile the estimated flow with an external estimate of the graduate entry level. Anchored, the mean graduate gap is a surplus of 946 a year. Unanchored, it is a shortage of 19.9. The sign reverses. The validation suite records this as a failure rather than as a caveat, and the anchor is documented in full at <span class="co">[</span><span class="ot">full report</span><span class="co">](/projects/teacher-forecasting/teacher_requirements_mainland_portugal_2025_2040.qmd)</span>.</span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a>The second is the descriptive student-teacher ratio. It records the staffing that occurred, including posts that went unfilled, so if the system was short of teachers during the observation window the ratio is biased upward and projected demand is biased downward. The mechanism is old and well documented: a system short of teachers adjusts by relaxing qualification requirements and raising the workload of the teachers it has, and those adjustments are absorbed into the observed ratio (Santiago, 2002). We impose no normative target anywhere in the chain. The requirement reported here is a lower bound.</span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>The third is the retirement hazard for the band aged 60 and above. It is set from the statutory exit age rather than estimated from the data, and the three estimated alternatives are all lower. That single assumption generates 94.7 per cent of the retirement wave, which in turn generates the recruitment requirement. Describing it as an estimate would be wrong.</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>Beyond the three, one quantity sits entirely outside every figure in this post. The substitution reserve, the pool of contracted teachers who cover absences and temporary vacancies during the school year, is not modelled at any point. At twenty per cent of the 2025 stock it would amount to 27,722 teachers, which is 4.10 times the shortfall the chain reports. The age-band sum of 139,098 on which the supply block works, and the reference census of approximately 122,000 active teachers in mainland public education, describe different universes, and comparisons that cross them are not like for like.</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a><span class="fu">## What transfers</span></span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>Three things about this exercise generalise to projections of the same family.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="al">![Variance decomposition of the projected deficits.](figures/variance_decomposition.png)</span>{#fig-variance width=100%}</span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>The variance decomposition inverts between the two deficits, as @fig-variance shows. On the graduate gap, the conversion rate accounts for 84.3 per cent of the variance; on the combined gap, the same parameter accounts for 3.5 per cent, while the lateral reserve accounts for 70.3 per cent. Reporting one decomposition therefore selects the answer by selecting the target. Any sensitivity analysis that names a single dominant driver should be read alongside the question of what deficit it was computed on.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>The validation suite reports sixteen passes among twenty evidential checks, not twenty-three among twenty-seven. Seven of the twenty-seven hold by construction: the quantities they compare are built from the same inputs and agree because the arithmetic requires it. A definition is not a finding, and counting it as one inflates the apparent standing of the result. The full count and the reasoning behind each exclusion are at <span class="in">`PROJECT_URL`</span>.</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>And a single organisational assumption moves the reference study's own requirement from 38,779 to between 15,579 and 16,474 (Nunes et al., 2025). Those alternative scenarios reallocate teachers' classroom availability fully to classroom needs. The range they open is larger than the entire gap between the two studies, which places roughly six in every ten projected recruitments in the domain of how schools are organised rather than in the domain of demography. The replacement and expansion decomposition used above is a standard international framing for exactly this reason (Bruneforth, Gagnon and Wallet, 2009): it separates what the population does from what the institution does.</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>You should use these figures as a lower bound on permanent posts under stated assumptions, not as a forecast of hires. The requirement is bounded below because the ratio is descriptive; the feasibility verdict flips sign if you remove the anchor; the deficit is zero if you net the channels; and the substitution reserve is absent throughout. If you disagree with the anchor, the ratio, or the channel split, the code is released so that the disagreement can be made precise.</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a><span class="fu">## References</span></span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Bruneforth, M., Gagnon, A. and Wallet, P. (2009). *Projecting the global demand for teachers: Meeting the goal of universal primary education by 2015*. Technical Paper No. 3. Montreal: UNESCO Institute for Statistics.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a>Nunes, L. C., Gomes, S., Capelo, C., Gião, J., Duarte, J., Ferreira, A. P. and Silva, P. L. (2025). *Estudo de diagnóstico de necessidades docentes de 2025 a 2034*. Lisbon: Direção-Geral de Estatísticas da Educação e Ciência.</span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>Richardson, S. and Tan, Y. (2007). *Forecasting future demands: What we can and cannot know*. Adelaide: National Centre for Vocational Education Research.</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>Santiago, P. (2002). *Teacher demand and supply: Improving teaching quality and addressing teacher shortages*. OECD Education Working Papers, No. 1. Paris: OECD Publishing. <span class="co">[</span><span class="ot">VERIFY</span><span class="co">]</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Â© 2026 JoÃ£o Vieira</p>
</div>   
    <div class="nav-footer-center">
<p>The Causal Layer â€” Applied writing on causal inference, pricing, and forecasting.</p>
</div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/joao-vieira-iseg/">
      <i class="bi bi-linkedin" role="img">
</i> 
    </a>
  </li>  
    <li class="nav-item compact">
    <a class="nav-link" href="mailto:joaoviei7a@gmail.com">
      <i class="bi bi-envelope" role="img">
</i> 
    </a>
  </li>  
</ul>
    </div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>